name: run main.py

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9]
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          Bearer_Token: ${{secrets.Bearer_Token}}
        run: timeout 300m python main.py || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
        # # The following works too, but it is not ideal since the error could be due to code issues and not timeout
        # timeout-minutes: 3
        # continue-on-error: true
        # run: python main.py
          
      - name: commit files
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -a -m "updated logs" --allow-empty
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Automatically created
          branch: main 